package models;
// Generated 24.02.2017 15:13:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Performer generated by hbm2java
 */
public class Performer  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String post;
     private String phoneIn;
     private String phoneOut;
     private String nickname;
     private Set documents = new HashSet(0);

    public Performer() {
    }

	
    public Performer(String name) {
        this.name = name;
    }
    public Performer(String name, String post, String phoneIn, String phoneOut, String nickname, Set documents) {
       this.name = name;
       this.post = post;
       this.phoneIn = phoneIn;
       this.phoneOut = phoneOut;
       this.nickname = nickname;
       this.documents = documents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public String getPhoneIn() {
        return this.phoneIn;
    }
    
    public void setPhoneIn(String phoneIn) {
        this.phoneIn = phoneIn;
    }
    public String getPhoneOut() {
        return this.phoneOut;
    }
    
    public void setPhoneOut(String phoneOut) {
        this.phoneOut = phoneOut;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


