package models;
// Generated 24.02.2017 15:13:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set documents = new HashSet(0);

    public Type() {
    }

	
    public Type(String name) {
        this.name = name;
    }
    public Type(String name, Set documents) {
       this.name = name;
       this.documents = documents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set documents) {
        this.documents = documents;
    }




}


